// flow-typed signature: 0696ad19091b5419a59271f3f12709ad
// flow-typed version: <<STUB>>/@types/react-navigation_v^1.0.32/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-navigation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-navigation' {
  declare module.exports: any;
}
