export const TV_SHOWS_FETCH_ALL = 'TV_SHOWS_FETCH_ALL'
export const TV_SHOWS_FETCH_FAILURE = 'TV_SHOWS_FETCH_FAILURE'
export const TV_SHOWS_RESULTS = 'TV_SHOWS_RESULTS'
export const TV_SHOWS_FETCH_GENRES = 'TV_SHOWS_FETCH_GENRES'

type TvShowActionType = TV_SHOWS_FETCH_ALL | TV_SHOWS_FETCH_FAILURE | TV_SHOWS_RESULTS | TV_SHOWS_FETCH_GENRES

export type { TvShowActionType }
