export const TV_SHOWS_FETCH_ALL = 'TV_SHOWS_FETCH_ALL'
export const TV_SHOWS_FETCH_FAILURE = 'TV_SHOWS_FETCH_FAILURE'
export const TV_SHOWS_RESULTS = 'TV_SHOWS_RESULTS'

type TvShowAction = TV_SHOWS_FETCH_ALL | TV_SHOWS_FETCH_FAILURE | TV_SHOWS_RESULTS

export type { TvShowAction }
